spring.application.name=processing-service
server.port=8082

# DATABASE
spring.datasource.url=jdbc:postgresql://localhost:5432/processing_db
spring.datasource.username=
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update

# KAFKA CONFIG
spring.kafka.bootstrap-servers=localhost:9092
app.kafka.topic.out=industria-carro
app.service.name=processing-service

# CONSUMER CONFIG (Lendo do RawMaterial)
spring.kafka.consumer.group-id=processing-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
# Mapeamento de ID para evitar erro de pacotes diferentes
spring.kafka.consumer.properties.spring.json.type.mapping=base_event:com.projeto.processingservice.dto.BaseEvent

# PRODUCER CONFIG (Enviando para Component)
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=true
spring.kafka.producer.properties.spring.json.type.mapping=base_event:com.projeto.processingservice.dto.BaseEvent
